# Spring Application Name
spring.application.name=techfest

# Default Tomcat Web Server Port
server.port=8081

# Enable Graceful Shutdown
server.shutdown=graceful

# Expose Actuator endpoints
management.endpoints.web.exposure.include=*

# Enable Tomcat MBean registry to expose metrics like tomcat.global.sent/received
server.tomcat.mbeanregistry.enabled=true

# Set clean disk space monitoring path to avoid trailing dots in metric names
management.metrics.system.diskspace.paths=/app


